services:
  sync:
    build: .
    env_file: .env.example
    ports:
      - '8000:8000'
    depends_on:
      - openldap
      - openwebui
  openldap:
    image: bitnami/openldap
    environment:
      - LDAP_ROOT=dc=example,dc=com
      - LDAP_ADMIN_USERNAME=admin
      - LDAP_ADMIN_PASSWORD=adminpassword
      - LDAP_ROOT_PASSWORD=adminpassword
      - LDAP_USERS=demo
      - LDAP_PASSWORDS=demopassword
  openwebui:
    image: ghcr.io/open-webui/open-webui
    ports:
      - '8080:8080'
