version: '3.8'
services:
  sync:
    build: .
    env_file: .env.example
    ports:
      - '8000:8000'
    depends_on:
      - openldap
      - openwebui
  openldap:
    image: bitnami/openldap
    environment:
      - LDAP_ADMIN_USERNAME=admin
      - LDAP_ADMIN_PASSWORD=adminpassword
      - LDAP_USERS=demo
  openwebui:
    image: ghcr.io/open-webui/open-webui
    ports:
      - '8080:8080'
