identity:
  user_attribute: mail
ldap:
  base_dn: dc=example,dc=com
  bind_dn: cn=admin,dc=example,dc=com
  bind_password: adminpassword
  group:
    membership_attr: member
    object_class: group
  tls:
    verify: false
  url: ldap://openldap:1389
  user_filter: (objectClass=user)
services:
- auth:
    api_key: Te8VQVIe6ESVsePxkjzN3BF8Tcliixu0oUkAhgta8fECkBQrq5ukrRE4TwaZVA7Q
  base_url: http://openwebui:8080
  group_mappings:
  - ldap_group_dn: cn=dep1,ou=groups,dc=example,dc=com
    target_group_name: Demo Group A
  - ldap_group_dn: cn=dep2,ou=groups,dc=example,dc=com
    target_group_name: Demo Group B
  http:
    request_timeout_seconds: 10
    verify_tls: false
  name: owui
  path_templates:
    add_user_to_group: /api/v1/groups/id/{group_id}/users/add
    group_users: /api/v1/groups/
    list_groups: /api/v1/groups/
    list_users: /api/v1/users/
    remove_user_from_group: /api/v1/groups/id/{group_id}/users/{user_id}/remove
  type: openwebui
sync:
  backoff_base_seconds: 0.5
  interval_seconds: 60
  max_backoff_seconds: 10
  retries: 3
version: 1
